# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
    ]
